export const REGISTRAR_MATRICULA = "REGISTRAR_MATRICULA";
export const REGISTRAR_ASISTENCIA = "REGISTRAR_ASISTENCIA";
export const MOSTRAR_MATRICULA = "MOSTRAR_MATRICULA";
export const MOSTRAR_ESTUDIANTE = "MOSTAR_ESTUDIANTE";
